version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: grupo43
      POSTGRES_USER: grupo43
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grupo43 -d grupo43"]
      interval: 5s
      retries: 5
      timeout: 5s

  flask_app:
    build:
      context: ./flask_app
    entrypoint: sh -c "flask --app app.web reset-db && flask --app app.web run --host=0.0.0.0 --port=5000"
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      PYTHONPATH: /app
      FLASK_ENV: development
      DATABASE_URL: postgresql://grupo43:1234@db:5432/grupo43
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: grupo43
      MINIO_SECRET_KEY: fierro123
    volumes:
      - ./flask_app:/app
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_docker
    environment:
      PGADMIN_DEFAULT_EMAIL: santiago.fierro99@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  minio:
    image: minio/minio
    container_name: minio_docker
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: grupo43
      MINIO_ROOT_PASSWORD: fierro123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

volumes:
  minio-data:


